disk: /dev/nvme0n1
hostname: joebutler
username: joebutler
locale: en_GB.UTF-8
keyboard_layout: uk
timezone: Europe/London
kernel: linux-zen
encryption: true
secure_boot: true
enable_zram: true
cpu_governor: ondemand
enable_tailscale: true
enable_syncthing: true
enable_firewall: true
enable_apparmor: true
enable_fail2ban: true
enable_snapper: true
auto_updates: true
btrfs_scrub: true
enable_reflector: true
dns_over_tls: true
dnssec: true
dotfiles_enabled: true
dotfiles_repository: git@github.com:joe-butler-23/.dotfiles
